// Generated by the protocol buffer compiler.  DO NOT EDIT!

#include "messages_robocup_ssl_wrapper.pb.h"
#include <google/protobuf/descriptor.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format_inl.h>

namespace {

const ::google::protobuf::Descriptor* SSL_WrapperPacket_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  SSL_WrapperPacket_reflection_ = NULL;

}  // namespace


void protobuf_BuildDesc_messages_5frobocup_5fssl_5fwrapper_2eproto_AssignGlobalDescriptors(const ::google::protobuf::FileDescriptor* file) {
  SSL_WrapperPacket_descriptor_ = file->message_type(0);
  SSL_WrapperPacket::default_instance_ = new SSL_WrapperPacket();
  static const int SSL_WrapperPacket_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_WrapperPacket, detection_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_WrapperPacket, geometry_),
  };
  SSL_WrapperPacket_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      SSL_WrapperPacket_descriptor_,
      SSL_WrapperPacket::default_instance_,
      SSL_WrapperPacket_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_WrapperPacket, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_WrapperPacket, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      sizeof(SSL_WrapperPacket));
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    SSL_WrapperPacket_descriptor_, SSL_WrapperPacket::default_instance_);
  SSL_WrapperPacket::default_instance_->InitAsDefaultInstance();
}

void protobuf_BuildDesc_messages_5frobocup_5fssl_5fwrapper_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;
  ::google::protobuf::DescriptorPool* pool =
    ::google::protobuf::DescriptorPool::internal_generated_pool();

  ::protobuf_BuildDesc_messages_5frobocup_5fssl_5fdetection_2eproto();
  ::protobuf_BuildDesc_messages_5frobocup_5fssl_5fgeometry_2eproto();
  pool->InternalBuildGeneratedFile(
    "\n\"messages_robocup_ssl_wrapper.proto\032$me"
    "ssages_robocup_ssl_detection.proto\032#mess"
    "ages_robocup_ssl_geometry.proto\"`\n\021SSL_W"
    "rapperPacket\022&\n\tdetection\030\001 \001(\0132\023.SSL_De"
    "tectionFrame\022#\n\010geometry\030\002 \001(\0132\021.SSL_Geo"
    "metryData", 209,
  &protobuf_BuildDesc_messages_5frobocup_5fssl_5fwrapper_2eproto_AssignGlobalDescriptors);
}

// Force BuildDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_messages_5frobocup_5fssl_5fwrapper_2eproto {
  StaticDescriptorInitializer_messages_5frobocup_5fssl_5fwrapper_2eproto() {
    protobuf_BuildDesc_messages_5frobocup_5fssl_5fwrapper_2eproto();
  }
} static_descriptor_initializer_messages_5frobocup_5fssl_5fwrapper_2eproto_;


// ===================================================================



SSL_WrapperPacket::SSL_WrapperPacket()
  : ::google::protobuf::Message(),
    _cached_size_(0),
    detection_(NULL),
    geometry_(NULL) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

void SSL_WrapperPacket::InitAsDefaultInstance() {  detection_ = const_cast< ::SSL_DetectionFrame*>(&::SSL_DetectionFrame::default_instance());
  geometry_ = const_cast< ::SSL_GeometryData*>(&::SSL_GeometryData::default_instance());
}

SSL_WrapperPacket::SSL_WrapperPacket(const SSL_WrapperPacket& from)
  : ::google::protobuf::Message(),
    _cached_size_(0),
    detection_(NULL),
    geometry_(NULL) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  MergeFrom(from);
}

SSL_WrapperPacket::~SSL_WrapperPacket() {
  if (this != default_instance_) {
    delete detection_;
    delete geometry_;
  }
}

const ::google::protobuf::Descriptor* SSL_WrapperPacket::descriptor() {
  if (SSL_WrapperPacket_descriptor_ == NULL) protobuf_BuildDesc_messages_5frobocup_5fssl_5fwrapper_2eproto();
  return SSL_WrapperPacket_descriptor_;
}

const SSL_WrapperPacket& SSL_WrapperPacket::default_instance() {
  if (default_instance_ == NULL) protobuf_BuildDesc_messages_5frobocup_5fssl_5fwrapper_2eproto();
  return *default_instance_;
}

SSL_WrapperPacket* SSL_WrapperPacket::default_instance_ = NULL;

SSL_WrapperPacket* SSL_WrapperPacket::New() const {
  return new SSL_WrapperPacket;
}

const ::google::protobuf::Descriptor* SSL_WrapperPacket::GetDescriptor() const {
  return descriptor();
}

const ::google::protobuf::Reflection* SSL_WrapperPacket::GetReflection() const {
  if (SSL_WrapperPacket_reflection_ == NULL) protobuf_BuildDesc_messages_5frobocup_5fssl_5fwrapper_2eproto();
  return SSL_WrapperPacket_reflection_;
}
