// Generated by the protocol buffer compiler.  DO NOT EDIT!

#include "messages_robocup_ssl_geometry.pb.h"
#include <google/protobuf/descriptor.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format_inl.h>

namespace {

const ::google::protobuf::Descriptor* SSL_GeometryFieldSize_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  SSL_GeometryFieldSize_reflection_ = NULL;
const ::google::protobuf::Descriptor* SSL_GeometryCameraCalibration_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  SSL_GeometryCameraCalibration_reflection_ = NULL;
const ::google::protobuf::Descriptor* SSL_GeometryData_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  SSL_GeometryData_reflection_ = NULL;

}  // namespace


void protobuf_BuildDesc_messages_5frobocup_5fssl_5fgeometry_2eproto_AssignGlobalDescriptors(const ::google::protobuf::FileDescriptor* file) {
  SSL_GeometryFieldSize_descriptor_ = file->message_type(0);
  SSL_GeometryFieldSize::default_instance_ = new SSL_GeometryFieldSize();
  static const int SSL_GeometryFieldSize_offsets_[14] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_GeometryFieldSize, line_width_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_GeometryFieldSize, field_length_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_GeometryFieldSize, field_width_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_GeometryFieldSize, boundary_width_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_GeometryFieldSize, referee_width_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_GeometryFieldSize, goal_width_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_GeometryFieldSize, goal_depth_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_GeometryFieldSize, goal_wall_width_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_GeometryFieldSize, center_circle_radius_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_GeometryFieldSize, defense_radius_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_GeometryFieldSize, defense_stretch_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_GeometryFieldSize, free_kick_from_defense_dist_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_GeometryFieldSize, penalty_spot_from_field_line_dist_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_GeometryFieldSize, penalty_line_from_spot_dist_),
  };
  SSL_GeometryFieldSize_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      SSL_GeometryFieldSize_descriptor_,
      SSL_GeometryFieldSize::default_instance_,
      SSL_GeometryFieldSize_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_GeometryFieldSize, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_GeometryFieldSize, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      sizeof(SSL_GeometryFieldSize));
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    SSL_GeometryFieldSize_descriptor_, SSL_GeometryFieldSize::default_instance_);
  SSL_GeometryCameraCalibration_descriptor_ = file->message_type(1);
  SSL_GeometryCameraCalibration::default_instance_ = new SSL_GeometryCameraCalibration();
  static const int SSL_GeometryCameraCalibration_offsets_[15] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_GeometryCameraCalibration, camera_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_GeometryCameraCalibration, focal_length_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_GeometryCameraCalibration, principal_point_x_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_GeometryCameraCalibration, principal_point_y_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_GeometryCameraCalibration, distortion_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_GeometryCameraCalibration, q0_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_GeometryCameraCalibration, q1_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_GeometryCameraCalibration, q2_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_GeometryCameraCalibration, q3_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_GeometryCameraCalibration, tx_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_GeometryCameraCalibration, ty_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_GeometryCameraCalibration, tz_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_GeometryCameraCalibration, derived_camera_world_tx_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_GeometryCameraCalibration, derived_camera_world_ty_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_GeometryCameraCalibration, derived_camera_world_tz_),
  };
  SSL_GeometryCameraCalibration_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      SSL_GeometryCameraCalibration_descriptor_,
      SSL_GeometryCameraCalibration::default_instance_,
      SSL_GeometryCameraCalibration_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_GeometryCameraCalibration, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_GeometryCameraCalibration, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      sizeof(SSL_GeometryCameraCalibration));
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    SSL_GeometryCameraCalibration_descriptor_, SSL_GeometryCameraCalibration::default_instance_);
  SSL_GeometryData_descriptor_ = file->message_type(2);
  SSL_GeometryData::default_instance_ = new SSL_GeometryData();
  static const int SSL_GeometryData_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_GeometryData, field_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_GeometryData, calib_),
  };
  SSL_GeometryData_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      SSL_GeometryData_descriptor_,
      SSL_GeometryData::default_instance_,
      SSL_GeometryData_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_GeometryData, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_GeometryData, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      sizeof(SSL_GeometryData));
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    SSL_GeometryData_descriptor_, SSL_GeometryData::default_instance_);
  SSL_GeometryFieldSize::default_instance_->InitAsDefaultInstance();
  SSL_GeometryCameraCalibration::default_instance_->InitAsDefaultInstance();
  SSL_GeometryData::default_instance_->InitAsDefaultInstance();
}

void protobuf_BuildDesc_messages_5frobocup_5fssl_5fgeometry_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;
  ::google::protobuf::DescriptorPool* pool =
    ::google::protobuf::DescriptorPool::internal_generated_pool();

  pool->InternalBuildGeneratedFile(
    "\n#messages_robocup_ssl_geometry.proto\"\212\003"
    "\n\025SSL_GeometryFieldSize\022\022\n\nline_width\030\001 "
    "\002(\005\022\024\n\014field_length\030\002 \002(\005\022\023\n\013field_width"
    "\030\003 \002(\005\022\026\n\016boundary_width\030\004 \002(\005\022\025\n\rrefere"
    "e_width\030\005 \002(\005\022\022\n\ngoal_width\030\006 \002(\005\022\022\n\ngoa"
    "l_depth\030\007 \002(\005\022\027\n\017goal_wall_width\030\010 \002(\005\022\034"
    "\n\024center_circle_radius\030\t \002(\005\022\026\n\016defense_"
    "radius\030\n \002(\005\022\027\n\017defense_stretch\030\013 \002(\005\022#\n"
    "\033free_kick_from_defense_dist\030\014 \002(\005\022)\n!pe"
    "nalty_spot_from_field_line_dist\030\r \002(\005\022#\n"
    "\033penalty_line_from_spot_dist\030\016 \002(\005\"\311\002\n\035S"
    "SL_GeometryCameraCalibration\022\021\n\tcamera_i"
    "d\030\001 \002(\r\022\024\n\014focal_length\030\002 \002(\002\022\031\n\021princip"
    "al_point_x\030\003 \002(\002\022\031\n\021principal_point_y\030\004 "
    "\002(\002\022\022\n\ndistortion\030\005 \002(\002\022\n\n\002q0\030\006 \002(\002\022\n\n\002q"
    "1\030\007 \002(\002\022\n\n\002q2\030\010 \002(\002\022\n\n\002q3\030\t \002(\002\022\n\n\002tx\030\n "
    "\002(\002\022\n\n\002ty\030\013 \002(\002\022\n\n\002tz\030\014 \002(\002\022\037\n\027derived_c"
    "amera_world_tx\030\r \001(\002\022\037\n\027derived_camera_w"
    "orld_ty\030\016 \001(\002\022\037\n\027derived_camera_world_tz"
    "\030\017 \001(\002\"h\n\020SSL_GeometryData\022%\n\005field\030\001 \002("
    "\0132\026.SSL_GeometryFieldSize\022-\n\005calib\030\002 \003(\013"
    "2\036.SSL_GeometryCameraCalibration", 872,
  &protobuf_BuildDesc_messages_5frobocup_5fssl_5fgeometry_2eproto_AssignGlobalDescriptors);
}

// Force BuildDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_messages_5frobocup_5fssl_5fgeometry_2eproto {
  StaticDescriptorInitializer_messages_5frobocup_5fssl_5fgeometry_2eproto() {
    protobuf_BuildDesc_messages_5frobocup_5fssl_5fgeometry_2eproto();
  }
} static_descriptor_initializer_messages_5frobocup_5fssl_5fgeometry_2eproto_;


// ===================================================================















SSL_GeometryFieldSize::SSL_GeometryFieldSize()
  : ::google::protobuf::Message(),
    _cached_size_(0),
    line_width_(0),
    field_length_(0),
    field_width_(0),
    boundary_width_(0),
    referee_width_(0),
    goal_width_(0),
    goal_depth_(0),
    goal_wall_width_(0),
    center_circle_radius_(0),
    defense_radius_(0),
    defense_stretch_(0),
    free_kick_from_defense_dist_(0),
    penalty_spot_from_field_line_dist_(0),
    penalty_line_from_spot_dist_(0) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

void SSL_GeometryFieldSize::InitAsDefaultInstance() {}

SSL_GeometryFieldSize::SSL_GeometryFieldSize(const SSL_GeometryFieldSize& from)
  : ::google::protobuf::Message(),
    _cached_size_(0),
    line_width_(0),
    field_length_(0),
    field_width_(0),
    boundary_width_(0),
    referee_width_(0),
    goal_width_(0),
    goal_depth_(0),
    goal_wall_width_(0),
    center_circle_radius_(0),
    defense_radius_(0),
    defense_stretch_(0),
    free_kick_from_defense_dist_(0),
    penalty_spot_from_field_line_dist_(0),
    penalty_line_from_spot_dist_(0) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  MergeFrom(from);
}

SSL_GeometryFieldSize::~SSL_GeometryFieldSize() {
  if (this != default_instance_) {
  }
}

const ::google::protobuf::Descriptor* SSL_GeometryFieldSize::descriptor() {
  if (SSL_GeometryFieldSize_descriptor_ == NULL) protobuf_BuildDesc_messages_5frobocup_5fssl_5fgeometry_2eproto();
  return SSL_GeometryFieldSize_descriptor_;
}

const SSL_GeometryFieldSize& SSL_GeometryFieldSize::default_instance() {
  if (default_instance_ == NULL) protobuf_BuildDesc_messages_5frobocup_5fssl_5fgeometry_2eproto();
  return *default_instance_;
}

SSL_GeometryFieldSize* SSL_GeometryFieldSize::default_instance_ = NULL;

SSL_GeometryFieldSize* SSL_GeometryFieldSize::New() const {
  return new SSL_GeometryFieldSize;
}

const ::google::protobuf::Descriptor* SSL_GeometryFieldSize::GetDescriptor() const {
  return descriptor();
}

const ::google::protobuf::Reflection* SSL_GeometryFieldSize::GetReflection() const {
  if (SSL_GeometryFieldSize_reflection_ == NULL) protobuf_BuildDesc_messages_5frobocup_5fssl_5fgeometry_2eproto();
  return SSL_GeometryFieldSize_reflection_;
}

// ===================================================================
















SSL_GeometryCameraCalibration::SSL_GeometryCameraCalibration()
  : ::google::protobuf::Message(),
    _cached_size_(0),
    camera_id_(0u),
    focal_length_(0),
    principal_point_x_(0),
    principal_point_y_(0),
    distortion_(0),
    q0_(0),
    q1_(0),
    q2_(0),
    q3_(0),
    tx_(0),
    ty_(0),
    tz_(0),
    derived_camera_world_tx_(0),
    derived_camera_world_ty_(0),
    derived_camera_world_tz_(0) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

void SSL_GeometryCameraCalibration::InitAsDefaultInstance() {}

SSL_GeometryCameraCalibration::SSL_GeometryCameraCalibration(const SSL_GeometryCameraCalibration& from)
  : ::google::protobuf::Message(),
    _cached_size_(0),
    camera_id_(0u),
    focal_length_(0),
    principal_point_x_(0),
    principal_point_y_(0),
    distortion_(0),
    q0_(0),
    q1_(0),
    q2_(0),
    q3_(0),
    tx_(0),
    ty_(0),
    tz_(0),
    derived_camera_world_tx_(0),
    derived_camera_world_ty_(0),
    derived_camera_world_tz_(0) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  MergeFrom(from);
}

SSL_GeometryCameraCalibration::~SSL_GeometryCameraCalibration() {
  if (this != default_instance_) {
  }
}

const ::google::protobuf::Descriptor* SSL_GeometryCameraCalibration::descriptor() {
  if (SSL_GeometryCameraCalibration_descriptor_ == NULL) protobuf_BuildDesc_messages_5frobocup_5fssl_5fgeometry_2eproto();
  return SSL_GeometryCameraCalibration_descriptor_;
}

const SSL_GeometryCameraCalibration& SSL_GeometryCameraCalibration::default_instance() {
  if (default_instance_ == NULL) protobuf_BuildDesc_messages_5frobocup_5fssl_5fgeometry_2eproto();
  return *default_instance_;
}

SSL_GeometryCameraCalibration* SSL_GeometryCameraCalibration::default_instance_ = NULL;

SSL_GeometryCameraCalibration* SSL_GeometryCameraCalibration::New() const {
  return new SSL_GeometryCameraCalibration;
}

const ::google::protobuf::Descriptor* SSL_GeometryCameraCalibration::GetDescriptor() const {
  return descriptor();
}

const ::google::protobuf::Reflection* SSL_GeometryCameraCalibration::GetReflection() const {
  if (SSL_GeometryCameraCalibration_reflection_ == NULL) protobuf_BuildDesc_messages_5frobocup_5fssl_5fgeometry_2eproto();
  return SSL_GeometryCameraCalibration_reflection_;
}

// ===================================================================



SSL_GeometryData::SSL_GeometryData()
  : ::google::protobuf::Message(),
    _cached_size_(0),
    field_(NULL) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

void SSL_GeometryData::InitAsDefaultInstance() {  field_ = const_cast< ::SSL_GeometryFieldSize*>(&::SSL_GeometryFieldSize::default_instance());
}

SSL_GeometryData::SSL_GeometryData(const SSL_GeometryData& from)
  : ::google::protobuf::Message(),
    _cached_size_(0),
    field_(NULL) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  MergeFrom(from);
}

SSL_GeometryData::~SSL_GeometryData() {
  if (this != default_instance_) {
    delete field_;
  }
}

const ::google::protobuf::Descriptor* SSL_GeometryData::descriptor() {
  if (SSL_GeometryData_descriptor_ == NULL) protobuf_BuildDesc_messages_5frobocup_5fssl_5fgeometry_2eproto();
  return SSL_GeometryData_descriptor_;
}

const SSL_GeometryData& SSL_GeometryData::default_instance() {
  if (default_instance_ == NULL) protobuf_BuildDesc_messages_5frobocup_5fssl_5fgeometry_2eproto();
  return *default_instance_;
}

SSL_GeometryData* SSL_GeometryData::default_instance_ = NULL;

SSL_GeometryData* SSL_GeometryData::New() const {
  return new SSL_GeometryData;
}

const ::google::protobuf::Descriptor* SSL_GeometryData::GetDescriptor() const {
  return descriptor();
}

const ::google::protobuf::Reflection* SSL_GeometryData::GetReflection() const {
  if (SSL_GeometryData_reflection_ == NULL) protobuf_BuildDesc_messages_5frobocup_5fssl_5fgeometry_2eproto();
  return SSL_GeometryData_reflection_;
}
