// Generated by the protocol buffer compiler.  DO NOT EDIT!

#include "messages_robocup_ssl_detection.pb.h"
#include <google/protobuf/descriptor.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format_inl.h>

namespace {

const ::google::protobuf::Descriptor* SSL_DetectionBall_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  SSL_DetectionBall_reflection_ = NULL;
const ::google::protobuf::Descriptor* SSL_DetectionRobot_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  SSL_DetectionRobot_reflection_ = NULL;
const ::google::protobuf::Descriptor* SSL_DetectionFrame_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  SSL_DetectionFrame_reflection_ = NULL;

}  // namespace


void protobuf_BuildDesc_messages_5frobocup_5fssl_5fdetection_2eproto_AssignGlobalDescriptors(const ::google::protobuf::FileDescriptor* file) {
  SSL_DetectionBall_descriptor_ = file->message_type(0);
  SSL_DetectionBall::default_instance_ = new SSL_DetectionBall();
  static const int SSL_DetectionBall_offsets_[7] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_DetectionBall, confidence_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_DetectionBall, area_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_DetectionBall, x_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_DetectionBall, y_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_DetectionBall, z_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_DetectionBall, pixel_x_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_DetectionBall, pixel_y_),
  };
  SSL_DetectionBall_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      SSL_DetectionBall_descriptor_,
      SSL_DetectionBall::default_instance_,
      SSL_DetectionBall_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_DetectionBall, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_DetectionBall, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      sizeof(SSL_DetectionBall));
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    SSL_DetectionBall_descriptor_, SSL_DetectionBall::default_instance_);
  SSL_DetectionRobot_descriptor_ = file->message_type(1);
  SSL_DetectionRobot::default_instance_ = new SSL_DetectionRobot();
  static const int SSL_DetectionRobot_offsets_[8] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_DetectionRobot, confidence_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_DetectionRobot, robot_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_DetectionRobot, x_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_DetectionRobot, y_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_DetectionRobot, orientation_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_DetectionRobot, pixel_x_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_DetectionRobot, pixel_y_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_DetectionRobot, height_),
  };
  SSL_DetectionRobot_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      SSL_DetectionRobot_descriptor_,
      SSL_DetectionRobot::default_instance_,
      SSL_DetectionRobot_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_DetectionRobot, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_DetectionRobot, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      sizeof(SSL_DetectionRobot));
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    SSL_DetectionRobot_descriptor_, SSL_DetectionRobot::default_instance_);
  SSL_DetectionFrame_descriptor_ = file->message_type(2);
  SSL_DetectionFrame::default_instance_ = new SSL_DetectionFrame();
  static const int SSL_DetectionFrame_offsets_[7] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_DetectionFrame, frame_number_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_DetectionFrame, t_capture_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_DetectionFrame, t_sent_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_DetectionFrame, camera_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_DetectionFrame, balls_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_DetectionFrame, robots_yellow_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_DetectionFrame, robots_blue_),
  };
  SSL_DetectionFrame_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      SSL_DetectionFrame_descriptor_,
      SSL_DetectionFrame::default_instance_,
      SSL_DetectionFrame_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_DetectionFrame, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SSL_DetectionFrame, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      sizeof(SSL_DetectionFrame));
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    SSL_DetectionFrame_descriptor_, SSL_DetectionFrame::default_instance_);
  SSL_DetectionBall::default_instance_->InitAsDefaultInstance();
  SSL_DetectionRobot::default_instance_->InitAsDefaultInstance();
  SSL_DetectionFrame::default_instance_->InitAsDefaultInstance();
}

void protobuf_BuildDesc_messages_5frobocup_5fssl_5fdetection_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;
  ::google::protobuf::DescriptorPool* pool =
    ::google::protobuf::DescriptorPool::internal_generated_pool();

  pool->InternalBuildGeneratedFile(
    "\n$messages_robocup_ssl_detection.proto\"x"
    "\n\021SSL_DetectionBall\022\022\n\nconfidence\030\001 \002(\002\022"
    "\014\n\004area\030\002 \001(\r\022\t\n\001x\030\003 \002(\002\022\t\n\001y\030\004 \002(\002\022\t\n\001z"
    "\030\005 \001(\002\022\017\n\007pixel_x\030\006 \002(\002\022\017\n\007pixel_y\030\007 \002(\002"
    "\"\227\001\n\022SSL_DetectionRobot\022\022\n\nconfidence\030\001 "
    "\002(\002\022\020\n\010robot_id\030\002 \001(\r\022\t\n\001x\030\003 \002(\002\022\t\n\001y\030\004 "
    "\002(\002\022\023\n\013orientation\030\005 \001(\002\022\017\n\007pixel_x\030\006 \002("
    "\002\022\017\n\007pixel_y\030\007 \002(\002\022\016\n\006height\030\010 \001(\002\"\331\001\n\022S"
    "SL_DetectionFrame\022\024\n\014frame_number\030\001 \002(\r\022"
    "\021\n\tt_capture\030\002 \002(\001\022\016\n\006t_sent\030\003 \002(\001\022\021\n\tca"
    "mera_id\030\004 \002(\r\022!\n\005balls\030\005 \003(\0132\022.SSL_Detec"
    "tionBall\022*\n\rrobots_yellow\030\006 \003(\0132\023.SSL_De"
    "tectionRobot\022(\n\013robots_blue\030\007 \003(\0132\023.SSL_"
    "DetectionRobot", 534,
  &protobuf_BuildDesc_messages_5frobocup_5fssl_5fdetection_2eproto_AssignGlobalDescriptors);
}

// Force BuildDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_messages_5frobocup_5fssl_5fdetection_2eproto {
  StaticDescriptorInitializer_messages_5frobocup_5fssl_5fdetection_2eproto() {
    protobuf_BuildDesc_messages_5frobocup_5fssl_5fdetection_2eproto();
  }
} static_descriptor_initializer_messages_5frobocup_5fssl_5fdetection_2eproto_;


// ===================================================================








SSL_DetectionBall::SSL_DetectionBall()
  : ::google::protobuf::Message(),
    _cached_size_(0),
    confidence_(0),
    area_(0u),
    x_(0),
    y_(0),
    z_(0),
    pixel_x_(0),
    pixel_y_(0) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

void SSL_DetectionBall::InitAsDefaultInstance() {}

SSL_DetectionBall::SSL_DetectionBall(const SSL_DetectionBall& from)
  : ::google::protobuf::Message(),
    _cached_size_(0),
    confidence_(0),
    area_(0u),
    x_(0),
    y_(0),
    z_(0),
    pixel_x_(0),
    pixel_y_(0) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  MergeFrom(from);
}

SSL_DetectionBall::~SSL_DetectionBall() {
  if (this != default_instance_) {
  }
}

const ::google::protobuf::Descriptor* SSL_DetectionBall::descriptor() {
  if (SSL_DetectionBall_descriptor_ == NULL) protobuf_BuildDesc_messages_5frobocup_5fssl_5fdetection_2eproto();
  return SSL_DetectionBall_descriptor_;
}

const SSL_DetectionBall& SSL_DetectionBall::default_instance() {
  if (default_instance_ == NULL) protobuf_BuildDesc_messages_5frobocup_5fssl_5fdetection_2eproto();
  return *default_instance_;
}

SSL_DetectionBall* SSL_DetectionBall::default_instance_ = NULL;

SSL_DetectionBall* SSL_DetectionBall::New() const {
  return new SSL_DetectionBall;
}

const ::google::protobuf::Descriptor* SSL_DetectionBall::GetDescriptor() const {
  return descriptor();
}

const ::google::protobuf::Reflection* SSL_DetectionBall::GetReflection() const {
  if (SSL_DetectionBall_reflection_ == NULL) protobuf_BuildDesc_messages_5frobocup_5fssl_5fdetection_2eproto();
  return SSL_DetectionBall_reflection_;
}

// ===================================================================









SSL_DetectionRobot::SSL_DetectionRobot()
  : ::google::protobuf::Message(),
    _cached_size_(0),
    confidence_(0),
    robot_id_(0u),
    x_(0),
    y_(0),
    orientation_(0),
    pixel_x_(0),
    pixel_y_(0),
    height_(0) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

void SSL_DetectionRobot::InitAsDefaultInstance() {}

SSL_DetectionRobot::SSL_DetectionRobot(const SSL_DetectionRobot& from)
  : ::google::protobuf::Message(),
    _cached_size_(0),
    confidence_(0),
    robot_id_(0u),
    x_(0),
    y_(0),
    orientation_(0),
    pixel_x_(0),
    pixel_y_(0),
    height_(0) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  MergeFrom(from);
}

SSL_DetectionRobot::~SSL_DetectionRobot() {
  if (this != default_instance_) {
  }
}

const ::google::protobuf::Descriptor* SSL_DetectionRobot::descriptor() {
  if (SSL_DetectionRobot_descriptor_ == NULL) protobuf_BuildDesc_messages_5frobocup_5fssl_5fdetection_2eproto();
  return SSL_DetectionRobot_descriptor_;
}

const SSL_DetectionRobot& SSL_DetectionRobot::default_instance() {
  if (default_instance_ == NULL) protobuf_BuildDesc_messages_5frobocup_5fssl_5fdetection_2eproto();
  return *default_instance_;
}

SSL_DetectionRobot* SSL_DetectionRobot::default_instance_ = NULL;

SSL_DetectionRobot* SSL_DetectionRobot::New() const {
  return new SSL_DetectionRobot;
}

const ::google::protobuf::Descriptor* SSL_DetectionRobot::GetDescriptor() const {
  return descriptor();
}

const ::google::protobuf::Reflection* SSL_DetectionRobot::GetReflection() const {
  if (SSL_DetectionRobot_reflection_ == NULL) protobuf_BuildDesc_messages_5frobocup_5fssl_5fdetection_2eproto();
  return SSL_DetectionRobot_reflection_;
}

// ===================================================================








SSL_DetectionFrame::SSL_DetectionFrame()
  : ::google::protobuf::Message(),
    _cached_size_(0),
    frame_number_(0u),
    t_capture_(0),
    t_sent_(0),
    camera_id_(0u) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

void SSL_DetectionFrame::InitAsDefaultInstance() {}

SSL_DetectionFrame::SSL_DetectionFrame(const SSL_DetectionFrame& from)
  : ::google::protobuf::Message(),
    _cached_size_(0),
    frame_number_(0u),
    t_capture_(0),
    t_sent_(0),
    camera_id_(0u) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  MergeFrom(from);
}

SSL_DetectionFrame::~SSL_DetectionFrame() {
  if (this != default_instance_) {
  }
}

const ::google::protobuf::Descriptor* SSL_DetectionFrame::descriptor() {
  if (SSL_DetectionFrame_descriptor_ == NULL) protobuf_BuildDesc_messages_5frobocup_5fssl_5fdetection_2eproto();
  return SSL_DetectionFrame_descriptor_;
}

const SSL_DetectionFrame& SSL_DetectionFrame::default_instance() {
  if (default_instance_ == NULL) protobuf_BuildDesc_messages_5frobocup_5fssl_5fdetection_2eproto();
  return *default_instance_;
}

SSL_DetectionFrame* SSL_DetectionFrame::default_instance_ = NULL;

SSL_DetectionFrame* SSL_DetectionFrame::New() const {
  return new SSL_DetectionFrame;
}

const ::google::protobuf::Descriptor* SSL_DetectionFrame::GetDescriptor() const {
  return descriptor();
}

const ::google::protobuf::Reflection* SSL_DetectionFrame::GetReflection() const {
  if (SSL_DetectionFrame_reflection_ == NULL) protobuf_BuildDesc_messages_5frobocup_5fssl_5fdetection_2eproto();
  return SSL_DetectionFrame_reflection_;
}
